remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: architecture-portfolio
description: 自分で設計したアーキテクチャと思考の記録
domain: txxxxc.github.io
url: https://txxxxc.github.io
baseurl: architecture-portfolio
